### ISSUE TITLE
AtCoder ProblemsへのAPIリクエストが失敗したときにコードが落ちる

### ISSUE THREAD

**Issue by kemuniku** [Thunder8110/Shojin-Point#3]
new_data[-1]を取得しようとして、newdataが{'message': 'Network error communicating with endpoint'}とかのせいで死ぬ

**Comment by Thunder8110** [comment]
私はこんなの `{'message': 'Endpoint request timed out'}` が出ました
何なんでしょうかね

**Comment by Thunder8110** [comment]
ちなみに、new_dataがエラーメッセージのときはtry-exceptで以降の処理をスキップしてはいます
それ以上にしないといけない処理があるって感じですか

**Comment by kemuniku** [comment]
え、僕が手元で編集してた部分がカスだったせいでした
あまりにごめんなさい
